### ISSUE TITLE
emacs-straight/org-mode is not updating

### ISSUE THREAD

**Issue by iyefrat** [raxod502/gnu-elpa-mirror#12]
Hey!
https://github.com/emacs-straight/org-mode is still on a commit from three weeks ago, even though the upstream repo has had a bunch of commits since. Other repos (e.g. corfu, tempel) have updated, but they all have their upstream URL as the ELPA URL, while org points to the org `cgit` repo. The last commit is on the day before af571207c9c0b00e3de9ab92474be16280d15909 got committed, so the issue is probably there, but from the code I'm not really sure what it would be.

**Comment by raxod502** [comment]
OK, I'll take a look - thanks for the report.

**Comment by raxod502** [comment]
Hmmm, it seems we have two separate repositories. I think the correct one is https://github.com/emacs-straight/org, while https://github.com/emacs-straight/org-mode is coming from somewhere else. Let me see why we have two...

**Comment by raxod502** [comment]
Ok, I guess based on the repository descriptions, https://github.com/emacs-straight/org is the ELPA version, which is tracked separately by the GNU folks, while https://github.com/emacs-straight/org-mode comes directly from upstream and is what `straight.el` uses by default when using the `org-elpa` recipe repository.

Since https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/ has recent commits but https://github.com/emacs-straight/org-mode doesn't, it seems like something has been lost in the mirroring logic. Yet the repository description is being updated...

**Comment by raxod502** [comment]
This is really interesting. For whatever reason, there is a bug in how certain types of updates are handled by the Git invocation run by GNU ELPA Mirror. I reproduced a similar issue when I ran locally, but when deleting the local checkout and letting it be cloned again, things worked.

When this application ran on Heroku, the entire working directory got wiped after every run. After I moved it to Railway, this no longer happens (though I didn't think through the implications of that at the time).

It would be ideal to avoid having to wipe the working directory, since then each run takes a lot longer, which is more expensive in terms of hosting costs. So let me see if I can work out the bug that is being encountered.

**Comment by raxod502** [comment]
OK, the problem is the Git commands I was using to `--mirror` Git repositories were just flat out wrong. I started https://github.com/radian-software/gnu-elpa-mirror/pull/13 to fix this issue and will finish it when I have a moment. In the meantime, I manually unstuck org-mode and cleared the Railway working directories, so we should be good until then at least.
