### ISSUE TITLE
No packages updated since January 13

### ISSUE THREAD

**Issue by fredericgiquel** [raxod502/gnu-elpa-mirror#14]
As we can see [here](https://github.com/orgs/emacs-straight/repositories), no update of the GNU ELPA mirror has been done for almost 3 weeks.

This is particularly problematic for the `compat` package because a recent version of which is required by other packages (`marginalia`, `consult`, ...)

**Comment by raxod502** [comment]
Yep, see https://github.com/radian-software/gnu-elpa-mirror/pull/13, I've been working on this but as of yet have not had the time to finish the changes. Sorry for the inconvenience.

**Comment by minad** [comment]
This issue has not been resolved. The ELPA mirror still hangs. See https://github.com/radian-software/straight.el/issues/1049.

**Comment by minad** [comment]
It seems the repositories were synchronized again yesterday after four days. @raxod502 Is this expected?

**Comment by raxod502** [comment]
Sigh, I keep thinking I fixed the issue and yet when the job runs as scheduled it runs into a new error. I'm really sorry for the inconvenience. Let me take another look.

**Comment by raxod502** [comment]
Okay, so I think the error that's showing up currently isn't what's being reported by users. It's org-mode failing to mirror, but that happens at the end (so other repos have already mirrored). Most likely what is causing complaints is the fact that I changed the cronjob to run every 3 days instead of every day, because another issue was causing the hosting bill to run up. However, I since put in a hack to sidestep that problem, I'll change it back to run every day.

**Comment by raxod502** [comment]
Sigh, I see this in the deployment environment:

![image](https://user-images.githubusercontent.com/6559064/219255343-2a59aff8-c809-438a-80b9-be2d112270c3.png)

I think the default branch name (which is different between the differing Git configs on my laptop and Railway) messes up the elaborate Git mirroring code I had to implement. Working on that.
