### ISSUE TITLE
Many packages out of date

### ISSUE THREAD

**Issue by tjtrabue** [raxod502/gnu-elpa-mirror#2]
Greetings! First of all, let me thank you for all of the amazing work you've put into `straight.el`. It's an amazing system, and it's supercharged my Emacs workflow. I've noticed that many packages in this mirror of ELPA are out of date (such as `xref`, which is only at version 1.0.2 in this mirror, but on ELPA it is up to version 1.1.0). Would you please consider updating each package in this repository?

Thank you so much,
-Tom

**Comment by raxod502** [comment]
Hey @tjtrabue! Sorry for the delay in getting back to you; I've been kept away by other things in my life for the last few months.

The GNU ELPA Mirror script runs daily, and I get alerted via email if it's been more than a week since a successful full update. So everything should be up to date relative to the upstream. If you're seeing out-of-date packages in your local Emacs, you probably just need to run `M-x straight-pull-package` or `M-x straight-pull-all` to fetch the latest version(s). In particular, xref was updated from 1.0.2 to 1.0.3 on 2020-08-27 (https://github.com/emacs-straight/xref/commit/81016e3f7a764a477ab08faec4631057a21b43cb), and the current version 1.1.0 was published on 2021-04-29 (https://github.com/emacs-straight/xref/commit/0fb98600927f6ba463f09c9df350e56b2ba23033).

**Comment by greg-minshall** [comment]
hi.  ditto on the thanks.  i wonder if the process is maybe wedged?  i'm looking for org 9.5, from gnu-elpa.  but, the last update of org (and, maybe other packages?) seems to be from 27 August.

cheers.

**Comment by raxod502** [comment]
Sorry about this! Indeed, mirroring started failing on 2021-08-29 and I simply hadn't gotten around to fixing it yet. I've done so now (see the recently pushed commits), and I've updated the script so it automatically includes the last update timestamp into every package repo description, so that it'll be obvious if things are broken or if you just need to pull new updates into your local Emacs.

Here's the new version of Org: https://github.com/emacs-straight/org

**Comment by raxod502** [comment]
Ah, looks like we've got two copies of Org, one from GNU ELPA and one from orgmode.org. Here's the latter updated as well: https://github.com/emacs-straight/org-mode

**Comment by greg-minshall** [comment]
great -- thanks!  (btw, fwiw, i think gnu elpa is, "going forward", the repository of choice.)

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
